print("SPIRA-X project 001 is running") 
name = input("What is your name? ")
problem = input("What business problem do you want to solve? ")
industry = input("What is industry are you in? ")
country = input("What country is the business located? ")
print()
print("REQUEST RECEIVED")
print("---------------")
print(f"customer: {name}")
print(f"problem: {problem}")
print(f"Industry: {industry}")
print(f"Country: {country}")
print()
print("SPIRA-X is processing your request...")
